# Generated by Django 5.1.7 on 2025-04-03 08:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0003_chathistory_disconnected_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chathistory",
            old_name="timestamp",
            new_name="created_at",
        ),
    ]
