# Generated by Django 5.1.7 on 2025-04-07 14:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0008_alter_flaggedemployeesummary_options_and_more"),
        ("employee", "0009_remove_employee_alertmessage"),
    ]

    operations = []
