# Generated by Django 5.1.7 on 2025-04-03 07:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chathistory",
            name="title",
        ),
    ]
