# Generated by Django 5.1.7 on 2025-04-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0002_remove_chathistory_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="chathistory",
            name="disconnected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
