# Generated by Django 5.2 on 2025-04-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_avg_work_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
    ]
