# Generated by Django 5.1.7 on 2025-04-01 20:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="avg_work_hours",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
