# Generated by Django 5.1.7 on 2025-04-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_customuser_avg_work_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="performance_activity",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
