# Generated by Django 5.2 on 2025-04-05 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_is_flagged'),
        ('accounts', '0003_customuser_performance_activity'),
    ]

    operations = [
    ]
