# Generated by Django 5.1.7 on 2025-04-07 20:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_merge_20250405_2158"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="mood_history",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
